settings:
  jump-power: 0.6
  enabled-by-default: true

particles:
  enabled: true
  type: CLOUD
  count: 15
  offset-x: 0.3
  offset-y: 0.2
  offset-z: 0.3
  speed: 0.02

sounds:
  enabled: true
  type: ENTITY_BAT_TAKEOFF
  volume: 0.6
  pitch: 1.5
