settings:
  jump-power: 2
  forward-power: 1.0
  enabled-by-default: true

particles:
  enabled: true
  type: crit
  count: 20
  offset-x: 0.3
  offset-y: 0.2
  offset-z: 0.3
  speed: 2

sounds:
  enabled: true
  type: entity.player.attack.crit
  volume: 5
  pitch: 1.2
